php:
 image: krisnantobiyuh/slim
 links:
  - db
 ports:
 - "8088:80"
 volumes:
 - ./:/var/www/html

db:
 image: mysql
 ports:
  - "8800:3306"
 environment:
  MYSQL_ROOT_PASSWORD: acer
 volumes:
 - ./mysql_data:/val/lib/mysql

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links: 
  - db
  ports:
  - "8008:80"
